"""
Django settings for Mazlofootwear project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2o@rnjjgq48p4+zpd^3qxi8=uix@bb)!srpy^mid9r8ujzua8+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.mazlofootwear.com', 'mazlofootwear.com', '127.0.0.1']

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
    '13.239.1.122'
    '0.0.0.0',         # sometimes needed
    '172.17.0.1',      # Docker host IP (example)
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my apps
    'Accounts',
    'About',
    'Home',
    'Blog',
    'Contact',
    'Career',
    'Shop',
    'Order',

    # third party apps
    'crispy_forms', 
    'debug_toolbar',   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # moved up here
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Mazlofootwear.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mazlofootwear.wsgi.application'


JAZZMIN_SETTINGS = {
    # UI Configuration
    "site_title": "Mazlo Admin Panel",
    "site_header": "Mazlo Admin",
    "site_brand": "Mazlo Panel",
    # "site_logo": "images/logo.jpg",  # Path to your logo
    "welcome_sign": "Welcome to Mazlo Admin Panel",
    "copyright": "Mazlo footwear",
    
    # UI Tweaks
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Icons Configuration
"icons": {
    # Auth
    "auth": "fas fa-shield-alt",
    "auth.user": "fas fa-user-tie",
    "auth.Group": "fas fa-users-cog",
    
    # Account app
    "Accounts.UserProfile": "fas fa-id-card",
    
    # Home app
    "Home.HeroBanner": "fas fa-ad",
    "Home.Category": "fas fa-layer-group",
    "Home.NewArrivalBanner": "fas fa-star",
    "Home.FeaturedCollection": "fas fa-tshirt",
    "Home.StyleJournal": "fas fa-paint-brush",

    # About app
    "About.Stat": "fas fa-chart-bar",
    "About.Journey": "fas fa-route",
    "About.GreenPromiseItem": "fas fa-recycle",
    "About.CoreValue": "fas fa-user-tie",
    
    # Blog app
    "Blog.Post": "fas fa-newspaper",
    "Blog.Blog_Category": "fas fa-tags",
    
    # Career app
    "Career.Job": "fas fa-user-tie",  
    "Career.Application": "fas fa-file-signature",
    
    # Contact app
    "Contact.Contact": "fas fa-envelope-open-text",
    
    # Shop App
    "Shop.Product": "fas fa-tshirt",
    "Shop.Category": "fas fa-boxes",  
    "Shop.Color": "fas fa-fill-drip",
    "Shop.ProductVariant": "fas fa-random",
    "Shop.Size": "fas fa-ruler-horizontal",
    "Shop.ProductImage": "fas fa-camera",
    
    # Order App
    "Order.Order": "fas fa-receipt",
    "Order.Cart": "fas fa-shopping-basket",
    "Order.OrderItem": "fas fa-box-open",
    "Order.Return": "fas fa-exchange-alt"
},
    
    # Theme Options
    "theme": "darkly",
    "changeform_format": "horizontal_tabs",
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mazlo',
        'USER': 'mazlo',
        'PASSWORD':'9947',
        'HOST': '127.0.0.1',  # If using a remote database, set the correct host
        'PORT': '5432',       # Default PostgreSQL port
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD':'Mazlofootwear123',
#         'HOST': 'mazlofootwear.cdca6kiwypeq.ap-southeast-2.rds.amazonaws.com',  # If using a remote database, set the correct host
#         'PORT': '5432',       # Default PostgreSQL port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Directory where collectstatic will collect static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional directories for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # or BASE_DIR / 'media' if you're using pathlib


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Backend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "mazlofootwear"
EMAIL_HOST_PASSWORD = "ucxr bfii ywwi dzhu"


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60 * 60 * 24,  # 24 hours default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of entries in the cache
        }
    }
}
