# Generated by Django 5.1.7 on 2025-04-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Blog Category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',), 'verbose_name_plural': 'Posts'},
        ),
    ]
