# Generated by Django 5.1.7 on 2025-11-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_category_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Blog.blog_category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img/'),
        ),
    ]
