# Generated by Django 5.1.7 on 2025-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('link', models.URLField(default='#')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
