# Generated by Django 5.1.7 on 2025-04-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='category/'),
        ),
    ]
