# Generated by Django 5.1.7 on 2025-04-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='new_arrivals/')),
                ('button_text', models.CharField(default='Quick View', max_length=20)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
