# Generated by Django 5.1.7 on 2025-05-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='journal/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
