# Generated by Django 5.1.7 on 2025-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='- Style & Design: Classic slip-on chappal with a sleek, minimalist silhouette—perfect for casual and semi-formal wear.\n        - Materials: Genuine leather upper with a soft, breathable lining; durable rubber outsole for superior grip.\n        - Comfort: Cushioned footbed with arch support helps reduce fatigue; lightweight construction for all-day wear.        \n        - Care: Wipe clean with a damp cloth; condition leather periodically to maintain finish.'),
        ),
    ]
