# Generated by Django 5.1.7 on 2025-11-01 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_payment_status'),
        ('Shop', '0003_alter_productvariant_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the cart item was created.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units of the product variant.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the cart item was last updated.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(help_text='The user who owns the cart.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(default=1, help_text='The specific product variant added to the cart.', on_delete=django.db.models.deletion.CASCADE, to='Shop.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='City for delivery.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Processing', help_text='Current status of the order.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='COD', help_text='Payment method used (e.g., COD, Card).', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Status of the payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number.', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(help_text='Shipping address for the order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(help_text='State for delivery.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount of the order.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='The user who placed the order.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(help_text='ZIP code for delivery.', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The order to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product at the time of ordering.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity of the product variant.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(default=1, help_text='The product variant ordered.', on_delete=django.db.models.deletion.CASCADE, to='Shop.productvariant'),
        ),
        migrations.AlterField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the return request was created.'),
        ),
        migrations.AlterField(
            model_name='return',
            name='description',
            field=models.TextField(help_text='Detailed description for the return request.'),
        ),
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.ForeignKey(help_text='The order being returned.', on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('wrong_size', 'Wrong Size'), ('damaged', 'Product Damaged'), ('not_as_described', 'Not As Described'), ('defective', 'Defective Product'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], help_text='Reason for return.', max_length=50),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', help_text='Status of the return request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='user',
            field=models.ForeignKey(help_text='The user requesting the return.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
